public class DashboardFrame extends javax.swing.JFrame {

    public DashboardFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSesiTest = new javax.swing.JButton();
        btnPeserta = new javax.swing.JButton();
        btnInputNilai = new javax.swing.JButton();
        btnHasilTest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard - Komputasi Nilai Test");
        setResizable(false);

        jPanel1.setVerifyInputWhenFocusTarget(false);

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplikasi Komputasi Nilai Test");

        logoutButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logout.png"))); // NOI18N
        logoutButton.setText("LOGOUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(logoutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutButton)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(2, 2));

        btnSesiTest.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSesiTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/test.png"))); // NOI18N
        btnSesiTest.setText("Sesi Test");
        btnSesiTest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSesiTest.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSesiTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesiTestActionPerformed(evt);
            }
        });
        jPanel2.add(btnSesiTest);

        btnPeserta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPeserta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/group.png"))); // NOI18N
        btnPeserta.setText("Peserta");
        btnPeserta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPeserta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPeserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesertaActionPerformed(evt);
            }
        });
        jPanel2.add(btnPeserta);

        btnInputNilai.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnInputNilai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/checklist.png"))); // NOI18N
        btnInputNilai.setText("Input Nilai Test");
        btnInputNilai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInputNilai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInputNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputNilaiActionPerformed(evt);
            }
        });
        jPanel2.add(btnInputNilai);

        btnHasilTest.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnHasilTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/analysis.png"))); // NOI18N
        btnHasilTest.setText("Hasil Test");
        btnHasilTest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHasilTest.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHasilTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHasilTestActionPerformed(evt);
            }
        });
        jPanel2.add(btnHasilTest);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.setVisible(false);
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void btnSesiTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesiTestActionPerformed
        this.setVisible(false);
        new SesiTestFrame().setVisible(true);
    }//GEN-LAST:event_btnSesiTestActionPerformed

    private void btnPesertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesertaActionPerformed
        this.setVisible(false);
        new PesertaFrame().setVisible(true);
    }//GEN-LAST:event_btnPesertaActionPerformed

    private void btnInputNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputNilaiActionPerformed
        this.setVisible(false);
        new InputNilaiFrame().setVisible(true);
    }//GEN-LAST:event_btnInputNilaiActionPerformed

    private void btnHasilTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHasilTestActionPerformed
        this.setVisible(false);
        new HasilTestFrame().setVisible(true);
    }//GEN-LAST:event_btnHasilTestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHasilTest;
    private javax.swing.JButton btnInputNilai;
    private javax.swing.JButton btnPeserta;
    private javax.swing.JButton btnSesiTest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutButton;
    // End of variables declaration//GEN-END:variables
}
